export const socialLinks = {
  instagram: "https://www.instagram.com/dukeimpactinvesting/",
  linkedin: "https://www.linkedin.com/company/diig/",
  email: "diigbd@gmail.com",
};

export const leadership = {
  partners: [
    { name: "Danielle Park", year: 2027 },
    { name: "Andy Li", year: 2026 },
    { name: "Alayna Binder", year: 2026 },
    { name: "Sreya Gnanavel", year: 2026 },
  ],
  directors: [
    { name: "Amy Liu", division: "Data" },
    { name: "Rocky Zhang", division: "Data" },
    { name: "Gabriela Nicolaievsky", division: "Consulting" },
    { name: "Shiv Batra", division: "Consulting" },
    { name: "Ella Veysel", division: "Business Development" },
    { name: "Sami Moudarres", division: "Business Development" },
    { name: "Jack Hirsh", division: "Investment" },
    { name: "Rendon Kuykendall", division: "Investment" },
    { name: "Suhaib Mansour", division: "Education" },
    { name: "Jimmy Helferty", division: "Education" },
    { name: "Anthony Lotruglio", division: "Treasurer" },
  ],
};

export const roster = {
  bd: [
    {
      name: "Ella Veysel",
      role: "Director",
      year: 2026,
      majors: "Risk, Data, and Financial Engineering",
      linkedin: "https://www.linkedin.com/in/ellaveysel",
      subdivision: "",
    },
    {
      name: "Sami Moudarres",
      role: "Director",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/sami-moudarres-833977276",
      subdivision: "",
    },
    {
      name: "Penelope James",
      role: "Project Manager",
      year: 2026,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/penelope-james-540012292",
      subdivision: "Marketing",
    },
    {
      name: "Rachel Talcoff",
      role: "Project Manager",
      year: 2027,
      majors: "Economics, Politial Science",
      linkedin: "https://www.linkedin.com/in/rachel-talcoff",
      subdivision: "Marketing",
    },
    {
      name: "Sean Clairine",
      role: "Analyst",
      year: 2028,
      majors: "Political Science",
      linkedin: "https://www.linkedin.com/in/seanclairine",
      subdivision: "Growth",
    },
    {
      name: "Mia Jantac",
      role: "Analyst",
      year: 2028,
      majors: "Neuroscience, Economics",
      linkedin: "https://www.linkedin.com/in/mia-jantac-294ba22b2",
      subdivision: "Growth",
    },
    {
      name: "Ceane Corbett",
      role: "Analyst",
      year: 2028,
      majors: "Economics, MMS Certificate",
      linkedin: "https://www.linkedin.com/in/ceane-corbett-b4bb91286",
      subdivision: "Growth",
    },
    {
      name: "Mika'il Naqvi",
      role: "Analyst",
      year: 2029,
      majors: "History & Economics",
      linkedin: "https://www.linkedin.com/in/mikailnaqvi78626",
      subdivision: "Growth",
    },
    {
      name: "Ahana Kotibhaskar",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/ahana-kotibhaskar-3619b3283",
      subdivision: "Growth",
    },
    {
      name: "Jacob Brill",
      role: "Analyst",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/jacobbrill",
      subdivision: "Growth",
    },
    {
      name: "Nathan Schwartz",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "Growth",
    },
    {
      name: "Julia Surzykiewicz",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "Growth",
    },
    {
      name: "Mia Liu",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "Growth",
    },
    {
      name: "Carina Kehoe",
      role: "Analyst",
      year: 2027,
      majors: "Economics, Politial Science",
      linkedin: "",
      subdivision: "Marketing",
    },
    {
      name: "Nilay Ghodasara",
      role: "Analyst",
      year: 2027,
      majors: "Economics, Public Policy",
      linkedin: "https://www.linkedin.com/in/nilayghodasara",
      subdivision: "Marketing",
    },
    {
      name: "Kevin Ma",
      role: "Analyst",
      year: 2028,
      majors: "Economics, Cinematic Arts",
      linkedin: "https://www.linkedin.com/in/kevin-ma-6a84792a2",
      subdivision: "Marketing",
    },
    {
      name: "Layelle Abou-Ezzi",
      role: "Analyst",
      year: 2028,
      majors: "Public Policy, Neuroscience",
      linkedin: "https://www.linkedin.com/in/layelleabouezzi",
      subdivision: "Marketing",
    },
    {
      name: "Hannah Shin",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/hannah-shin-96b49832b",
      subdivision: "Marketing",
    },
    {
      name: "Ethan Jiang",
      role: "Analyst",
      year: 2029,
      majors: "Economics?",
      linkedin: "https://www.linkedin.com/in/ethannjiang",
      subdivision: "Marketing",
    },
    {
      name: "Ally Reich",
      role: "Analyst",
      year: 2028,
      majors: "Psychology and Markets & Management",
      linkedin: "https://www.linkedin.com/in/ally-reich-84b656382",
      subdivision: "Marketing",
    },
    {
      name: "Cecily Burns",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "Marketing",
    },
    {
      name: "Annabelle Wei",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "Marketing",
    },
    {
      name: "Allison Hu",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "Marketing",
    },
    {
      name: "Claire Peng",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "Open",
    },
    {
      name: "Charlyn Chu",
      role: "PREV GROWTH PM",
      year: 2028,
      majors: "Economics, Statistics",
      linkedin: "https://www.linkedin.com/in/charlynchu",
      subdivision: "Growth",
    },
    {
      name: "Reeha Rahman",
      role: "Analyst",
      year: 2029,
      majors: "Neuroscience",
      linkedin: "https://www.linkedin.com/in/reeharahman",
      subdivision: "",
    },
  ],
  data: [
    {
      name: "Amy Liu",
      role: "Co-Director",
      year: 2027,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/amyhliu27",
      subdivision: "",
    },
    {
      name: "Rocky Zhang",
      role: "Co-Director",
      year: 2027,
      majors: "Math + CS + PoliSci",
      linkedin: "https://www.linkedin.com/in/lirockyzhang",
      subdivision: "",
    },
    {
      name: "Sahil Patel",
      role: "PM",
      year: 2027,
      majors: "Math + CS",
      linkedin: "https://www.linkedin.com/in/sahil-patel-4ab71320a",
      subdivision: "",
    },
    {
      name: "Aarsh Roongta",
      role: "PM",
      year: 2028,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/aarsh-roongta",
      subdivision: "",
    },
    {
      name: "Soham Jinsi",
      role: "PM",
      year: 2028,
      majors: "Math + CS",
      linkedin: "https://www.linkedin.com/in/soham-jinsi",
      subdivision: "",
    },
    {
      name: "Edward Song",
      role: "PM",
      year: 2028,
      majors: "Stats + Econ",
      linkedin: "https://www.linkedin.com/in/edward-song-7627182b1",
      subdivision: "",
    },
    {
      name: "Amogh Manral",
      role: "PM",
      year: 2028,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/amogh-manral-688736248",
      subdivision: "",
    },
    {
      name: "David Li",
      role: "PM",
      year: 2028,
      majors: "CS + Econ",
      linkedin: "https://www.linkedin.com/in/david-x-li",
      subdivision: "",
    },
    {
      name: "Yule Fu",
      role: "PM",
      year: 2027,
      majors: "Math + Stats",
      linkedin: "https://www.linkedin.com/in/yule-fu-1230ml",
      subdivision: "",
    },
    {
      name: "Beatrice Ghosn",
      role: "PM",
      year: 2027,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/beatrice-ghosn",
      subdivision: "",
    },
    {
      name: "Ian Le",
      role: "Operations",
      year: 2028,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/ian-le",
      subdivision: "",
    },
    {
      name: "Samya Chauhan",
      role: "Data Analyst",
      year: 2028,
      majors: "CS + Finance",
      linkedin: "https://www.linkedin.com/in/samyachauhan",
      subdivision: "",
    },
    {
      name: "Shravan Selvavel",
      role: "Data Analyst",
      year: 2028,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/shravan-selvavel-698712247",
      subdivision: "",
    },
    {
      name: "Liane Ma",
      role: "Data Analyst",
      year: 2027,
      majors: "Stats",
      linkedin: "https://www.linkedin.com/in/lianema",
      subdivision: "",
    },
    {
      name: "Jacky Yang",
      role: "Data Analyst",
      year: 2029,
      majors: "CS + Econ",
      linkedin: "https://www.linkedin.com/in/jacky-yang-duke",
      subdivision: "",
    },
    {
      name: "Rohith Kumar",
      role: "Data Analyst",
      year: 2029,
      majors: "ECE+CS",
      linkedin: "https://www.linkedin.com/in/rohith-kumar-911949249",
      subdivision: "",
    },
    {
      name: "Arihant Rajesh",
      role: "Data Analyst",
      year: 2029,
      majors: "BME + CS",
      linkedin: "https://www.linkedin.com/in/arihant-r-4360732ba",
      subdivision: "",
    },
    {
      name: "Parker Hayashi",
      role: "Data Analyst",
      year: 2029,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/parkerhayashi",
      subdivision: "",
    },
    {
      name: "Mahima Gyamlani",
      role: "Data Analyst",
      year: 2028,
      majors: "CS+Stat",
      linkedin: "https://www.linkedin.com/in/mahimagyamlani",
      subdivision: "",
    },
    {
      name: "Keith LoboPrabhu",
      role: "Data Analyst",
      year: 2029,
      majors: "Econ + PubPol",
      linkedin: "https://www.linkedin.com/in/keithloboprabhu",
      subdivision: "",
    },
    {
      name: "Bella Raymond",
      role: "Data Analyst",
      year: 2028,
      majors: "ECE",
      linkedin: "https://www.linkedin.com/in/isabelle-raymond-144390374",
      subdivision: "",
    },
    {
      name: "Ashley Park",
      role: "Data Analyst",
      year: 2028,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/ashleyebpark",
      subdivision: "",
    },
    {
      name: "James Wright",
      role: "Data Analyst",
      year: 2029,
      majors: "CS + Math",
      linkedin: "https://www.linkedin.com/in/james-wright-7798a4326",
      subdivision: "",
    },
    {
      name: "Sebastian Estrada",
      role: "Data Analyst",
      year: 2029,
      majors: "ECE + Math",
      linkedin: "https://www.linkedin.com/in/sebastian-estrada-9875ab307",
      subdivision: "",
    },
    {
      name: "Ashia Agarwal",
      role: "Data Analyst",
      year: 2029,
      majors: "CS + Math",
      linkedin: "https://www.linkedin.com/in/ashia-agarwal-35b93321a",
      subdivision: "",
    },
    {
      name: "Simon Stryszak",
      role: "Data Analyst",
      year: 2028,
      majors: "BME + Econ",
      linkedin: "https://www.linkedin.com/in/simon-stryszak-51535b325",
      subdivision: "",
    },
    {
      name: "Amy Xu",
      role: "Data Analyst",
      year: 2027,
      majors: "Stats",
      linkedin: "https://www.linkedin.com/in/amy-xu-924769291",
      subdivision: "",
    },
    {
      name: "Tally Coulter",
      role: "Data Analyst",
      year: 2027,
      majors: "Stats",
      linkedin: "https://www.linkedin.com/in/natalie-coulterr",
      subdivision: "",
    },
    {
      name: "Manya Bhagat",
      role: "Data Analyst",
      year: 2028,
      majors: "CS + Econ",
      linkedin: "https://www.linkedin.com/in/manya-bhagat",
      subdivision: "",
    },
    {
      name: "Rithika Saravanan",
      role: "Data Analyst",
      year: 2027,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/rithika-saravanan",
      subdivision: "",
    },
    {
      name: "Andy Sun",
      role: "Data Analyst",
      year: 2029,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/andy-sun-7b75a9266",
      subdivision: "",
    },
    {
      name: "Ian Prazak",
      role: "Data Analyst",
      year: 2029,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/ian-prazak-02303027a",
      subdivision: "",
    },
    {
      name: "Shreyan Singha",
      role: "Data Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Aashiv Jain",
      role: "Data Analyst",
      year: 2029,
      majors: "CS + Stats",
      linkedin: "https://www.linkedin.com/in/aashiv-jain",
      subdivision: "",
    },
    {
      name: "Anusha Kamath",
      role: "Data Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Rachel Yu",
      role: "Data Analyst",
      year: 2028,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Hanna Chee",
      role: "Data Analyst",
      year: 2029,
      majors: "Stats",
      linkedin: "https://www.linkedin.com/in/hanna-chee-496461387",
      subdivision: "",
    },
    {
      name: "Ronit Dey",
      role: "Data Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Echo Li",
      role: "Data Analyst",
      year: 2027,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Sophie Xu",
      role: "Data Analyst",
      year: 2027,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Anoushka Chaudhury",
      role: "Data Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Pramya Surapaneni",
      role: "Data Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
  ],
  investment: [
    {
      name: "Cheyenne  Tan",
      role: "Analyst",
      year: 2028,
      majors: "BME, I&E, computational bio",
      linkedin: "",
      subdivision: "Tech",
    },
    {
      name: "Dev Dwivedy",
      role: "Analyst",
      year: 2029,
      majors: "Computer Science and Economics",
      linkedin: "",
      subdivision: "Sports, Media, & Entertainment",
    },
    {
      name: "Jiaheng Yin",
      role: "Analyst",
      year: 2028,
      majors: "Econ & PubPol",
      linkedin: "",
      subdivision: "Industrials",
    },
    {
      name: "Kate Foster",
      role: "Analyst",
      year: 2029,
      majors: "Econ/Political Science",
      linkedin: "",
      subdivision: "Healthcare",
    },
    {
      name: "Devansh Roongta",
      role: "Analyst",
      year: 2029,
      majors: "Economics + CS",
      linkedin: "",
      subdivision: "Fintech",
    },
    {
      name: "Jay Patel",
      role: "Analyst",
      year: 2029,
      majors: "Economics and Computer Science",
      linkedin: "",
      subdivision: "Portfolio Management",
    },
    {
      name: "Daniel McNair",
      role: "Analyst",
      year: 2028,
      majors: "Financial Economics",
      linkedin: "",
      subdivision: "Industrials",
    },
    {
      name: "Maxwell Hyman",
      role: "Analyst",
      year: 2027,
      majors: "Econ/Stats",
      linkedin: "",
      subdivision: "Industrials",
    },
    {
      name: "Belle Phang",
      role: "Analyst",
      year: 2029,
      majors: "Mechanical Engineering, Energy Engineering",
      linkedin: "",
      subdivision: "Fintech",
    },
    {
      name: "Max Kelner",
      role: "Analyst",
      year: 2029,
      majors: "Econ with a Finance Concentration",
      linkedin: "",
      subdivision: "Energy",
    },
    {
      name: "Aidan Shen",
      role: "Analyst",
      year: 2029,
      majors: "Math & Econ",
      linkedin: "",
      subdivision: "Healthcare",
    },
    {
      name: "Story Kummer",
      role: "Analyst",
      year: 2029,
      majors: "Economics and poly sci",
      linkedin: "",
      subdivision: "Consumer",
    },
    {
      name: "Advika Arya",
      role: "Analyst",
      year: 2029,
      majors: "CS & Econ",
      linkedin: "",
      subdivision: "Tech",
    },
    {
      name: "Ashok Mittal",
      role: "Analyst",
      year: 2029,
      majors: "Economics, Math",
      linkedin: "",
      subdivision: "Energy",
    },
    {
      name: "Alice  Karas",
      role: "Analyst",
      year: 2029,
      majors: "Undecided",
      linkedin: "",
      subdivision: "Sports, Media, & Entertainment",
    },
    {
      name: "Isaac Lief",
      role: "Analyst",
      year: 2028,
      majors: "CS/Stats",
      linkedin: "",
      subdivision: "Tech",
    },
    {
      name: "Paige LaForge",
      role: "Analyst",
      year: 2029,
      majors:
        "Major: Economics, Minors: Spanish, Environmental Sciences and Policy",
      linkedin: "",
      subdivision: "Energy",
    },
    {
      name: "Grace Ren",
      role: "Analyst",
      year: 2029,
      majors: "Major: Econ | Minor: Latin",
      linkedin: "",
      subdivision: "Sports, Media, & Entertainment",
    },
    {
      name: "Ethan Haas",
      role: "Analyst",
      year: 2029,
      majors: "Econ/English",
      linkedin: "",
      subdivision: "Fintech",
    },
    {
      name: "Ella Wang",
      role: "Analyst",
      year: 2029,
      majors: "Public Policy and Economics",
      linkedin: "",
      subdivision: "Consumer",
    },
    {
      name: "Jack Shaw",
      role: "PM",
      year: 2028,
      majors: "Data Science",
      linkedin: "",
      subdivision: "Healthcare",
    },
    {
      name: "Hale Snyder",
      role: "PM",
      year: 2028,
      majors: "Economics, energy and the environment",
      linkedin: "",
      subdivision: "Industrials",
    },
    {
      name: "Lawrence Gardner",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "",
      subdivision: "Sports, Media, & Entertainment",
    },
    {
      name: "Leyuan Zhou",
      role: "Analyst",
      year: 2029,
      majors: "Neuroscience & Economics",
      linkedin: "",
      subdivision: "Industrials",
    },
    {
      name: "Alex Wagonfeld",
      role: "PM",
      year: 2028,
      majors: "Economics, Energy & Environment Certificate",
      linkedin: "",
      subdivision: "Fintech",
    },
    {
      name: "Charlie Pausic",
      role: "PM",
      year: 2028,
      majors: "Economics",
      linkedin: "",
      subdivision: "Sports, Media, & Entertainment",
    },
    {
      name: "Matthew Roberts",
      role: "PM",
      year: 2028,
      majors: "Economics Major",
      linkedin: "",
      subdivision: "Tech",
    },
    {
      name: "Andy Li",
      role: "PM",
      year: 2028,
      majors: "Economics and Computer Science",
      linkedin: "",
      subdivision: "Portfolio Management",
    },
    {
      name: "Lilla Timperman",
      role: "PM",
      year: 2026,
      majors: "Political Science, Financial Economics",
      linkedin: "",
      subdivision: "Portfolio Management",
    },
    {
      name: "Juhyun Nam",
      role: "Analyst",
      year: 2029,
      majors: "Econ + CS",
      linkedin: "",
      subdivision: "Portfolio Management",
    },
    {
      name: "Varenya Katta",
      role: "Analyst",
      year: 2029,
      majors: "Economics and Neuroscience",
      linkedin: "",
      subdivision: "Healthcare",
    },
    {
      name: "Sajan Patel",
      role: "Analyst",
      year: 2029,
      majors: "Financial Economics, Energy & Climate Certificate",
      linkedin: "",
      subdivision: "Consumer",
    },
    {
      name: "Asher Schenk",
      role: "Analyst",
      year: 2029,
      majors: "Financial Economics",
      linkedin: "",
      subdivision: "Consumer",
    },
    {
      name: "Karim Wortelboer",
      role: "Analyst",
      year: 2028,
      majors: "Economics / CS",
      linkedin: "",
      subdivision: "Energy",
    },
    {
      name: "Eleana Yu",
      role: "PM",
      year: 2027,
      majors: "Economics/MMS",
      linkedin: "",
      subdivision: "Consumer",
    },
    {
      name: "Pierce Satsky",
      role: "Analyst",
      year: 2028,
      majors: "Economics",
      linkedin: "",
      subdivision: "Consumer",
    },
    {
      name: "Mohith Gajjela",
      role: "Analyst",
      year: 2029,
      majors: "Econ & CS",
      linkedin: "",
      subdivision: "Tech",
    },
    {
      name: "Jeffrey Huang",
      role: "PM",
      year: 2027,
      majors: "Financial Economics and Chemistry Minor",
      linkedin: "",
      subdivision: "Energy",
    },
    {
      name: "Rashmi Thapa",
      role: "PM",
      year: 2028,
      majors: "Economics + Computer Science",
      linkedin: "",
      subdivision: "Tech",
    },
    {
      name: "Rendon Kuykendall",
      role: "Director",
      year: 2027,
      majors: "Pub Pol + Econ",
      linkedin: "https://www.linkedin.com/in/rendon-kuykendall",
      subdivision: "",
    },
  ],
  education: [
    {
      name: "Suhaib Mansour",
      role: "Co-Director",
      year: 2028,
      majors: "Mathematics",
      linkedin: "https://www.linkedin.com/in/suhaib-mansour-705117303",
      subdivision: "",
    },
    {
      name: "Evan Glasberg",
      role: "",
      year: 2028,
      majors: "Economics and Political Science",
      linkedin: "https://www.linkedin.com/in/evan-glasberg-b168952ab",
      subdivision: "",
    },
    {
      name: "Hardit Bhutani",
      role: "",
      year: 2029,
      majors: "Biology, Statistics",
      linkedin: "https://www.linkedin.com/in/hardit-bhutani",
      subdivision: "",
    },
    {
      name: "Owen Banks",
      role: "",
      year: 2029,
      majors: "Mathematics, Economics",
      linkedin: "https://www.linkedin.com/in/owen-banks-a0a03337a",
      subdivision: "",
    },
    {
      name: "Nikhilesh Kalyanaraman",
      role: "PM",
      year: 2029,
      majors: "Financial Economics and Political Science",
      linkedin: "https://www.linkedin.com/in/nikhilesh-kalyanaraman-93057526a",
      subdivision: "",
    },
    {
      name: "Aarav Mehta",
      role: "",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/aarav-mehta-30a613295",
      subdivision: "",
    },
    {
      name: "Brian Cha",
      role: "",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/brian-cha-86454235a",
      subdivision: "",
    },
    {
      name: "Jimmy Helferty",
      role: "Co-Director",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/jimmy-helferty-a709a6283",
      subdivision: "",
    },
    {
      name: "Aditi Hongalgi",
      role: "",
      year: 2029,
      majors: "Economics, Environmental Science and Policy",
      linkedin: "https://www.linkedin.com/in/aditi-hongalgi",
      subdivision: "",
    },
    {
      name: "Daud Malik",
      role: "",
      year: 2028,
      majors: "Chemistry, Public Policy",
      linkedin: "https://www.linkedin.com/in/daudmalik",
      subdivision: "",
    },
    {
      name: "Rajit Jain",
      role: "",
      year: 2027,
      majors: "Economics; Computer Science",
      linkedin: "https://www.linkedin.com/in/rajit-jain",
      subdivision: "",
    },
    {
      name: "Tony Liu",
      role: "",
      year: 2029,
      majors: "Economics & Public Policy",
      linkedin: "https://www.linkedin.com/in/tonyliu-duke",
      subdivision: "",
    },
    {
      name: "Avi Karamchandani",
      role: "",
      year: 2029,
      majors: "Mathematics, Economics",
      linkedin: "https://www.linkedin.com/in/avi-karamchandani",
      subdivision: "",
    },
    {
      name: "Nahom Theodros",
      role: "",
      year: 2028,
      majors: "Computer Science",
      linkedin: "https://www.linkedin.com/in/nahom-theodros",
      subdivision: "",
    },
    {
      name: "Andrew Noah Rodrigues Ferreira",
      role: "",
      year: 2029,
      majors: "Computer Science, Math",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Carson Eisner",
      role: "",
      year: 2029,
      majors: "Economics + Math",
      linkedin: "https://www.linkedin.com/in/carsoneisner",
      subdivision: "",
    },
    {
      name: "Apollo Lee",
      role: "",
      year: 2029,
      majors: "Stats and Math",
      linkedin: "https://www.linkedin.com/in/apollo-lee-1954ba348",
      subdivision: "",
    },
    {
      name: "Kabir Sankaran Rajendra",
      role: "",
      year: 2029,
      majors: "Math",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Evan Lehmann",
      role: "",
      year: 2028,
      majors: "Economics and Education",
      linkedin: "https://www.linkedin.com/in/evan-lehmann-275797326",
      subdivision: "",
    },
    {
      name: "Sophia Lynn",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
  ],
  consulting: [
    {
      name: "Shreya Nallamothu",
      role: "Analyst",
      year: 2029,
      majors: "Computer Science, Public Policy",
      linkedin: "https://www.linkedin.com/in/shreyanallamothu",
      subdivision: "",
    },
    {
      name: "Anthony Benbenek",
      role: "PM",
      year: 2028,
      majors: "PolSci and Econ",
      linkedin: "https://www.linkedin.com/in/anthony-a-benbenek-8b5098327",
      subdivision: "",
    },
    {
      name: "Claire Chen",
      role: "Analyst",
      year: 2028,
      majors: "Econ & English",
      linkedin: "https://www.linkedin.com/in/claire-chen-1b5277327",
      subdivision: "",
    },
    {
      name: "Brianna yang",
      role: "Analyst",
      year: 2028,
      majors: "Pub pol and cs",
      linkedin: "https://www.linkedin.com/in/brianna-c-yang",
      subdivision: "",
    },
    {
      name: "Eric Min",
      role: "PM",
      year: 2027,
      majors: "Economics, stats minor",
      linkedin: "https://www.linkedin.com/in/jaehong-min",
      subdivision: "",
    },
    {
      name: "Aditi Vikram",
      role: "Analyst",
      year: 2029,
      majors: "Econ and Environmental Science & Policy",
      linkedin: "https://www.linkedin.com/in/aditi-vikram-duke2029",
      subdivision: "",
    },
    {
      name: "May Lou",
      role: "Analyst",
      year: 2029,
      majors: "Public Policy, Statistics",
      linkedin: "https://www.linkedin.com/in/may-lou-12b5b1382",
      subdivision: "",
    },
    {
      name: "Madeleine Dean",
      role: "PM",
      year: 2026,
      majors: "Public Policy, Environmental Sciences and Policy",
      linkedin: "https://www.linkedin.com/in/madeleine-d-3b7b07204",
      subdivision: "",
    },
    {
      name: "Hayden Chang",
      role: "Analyst",
      year: 2029,
      majors: "Political Science",
      linkedin: "https://www.linkedin.com/in/haydenchang",
      subdivision: "",
    },
    {
      name: "Chloe Chun",
      role: "PM",
      year: 2028,
      majors: "Econ + Computational Media",
      linkedin: "https://www.linkedin.com/in/chloetchun",
      subdivision: "",
    },
    {
      name: "Raahi Soni",
      role: "Analyst",
      year: 2029,
      majors: "Economics and Statistics",
      linkedin: "https://www.linkedin.com/in/raahisoni",
      subdivision: "",
    },
    {
      name: "Juhee Grace Kim",
      role: "PM",
      year: 2029,
      majors: "Statistics and Philosophy",
      linkedin: "https://www.linkedin.com/in/juhee-kim-a7a47a34a",
      subdivision: "",
    },
    {
      name: "Owen Liu",
      role: "Analyst",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/oliuowen",
      subdivision: "",
    },
    {
      name: "Carson Cattano",
      role: "Analyst",
      year: 2029,
      majors: "Econ & Philosophy",
      linkedin: "https://www.linkedin.com/in/carson-cattano-b80160241",
      subdivision: "",
    },
    {
      name: "Ella Bilu",
      role: "Analyst",
      year: 2029,
      majors: "Public Policy and Journalism and Media",
      linkedin: "https://www.linkedin.com/in/ella-bilu-a51643220",
      subdivision: "",
    },
    {
      name: "Ryan Hahm",
      role: "Analyst",
      year: 2029,
      majors: "Econ and Stat Minor",
      linkedin: "https://www.linkedin.com/in/ryan-hahm-duke",
      subdivision: "",
    },
    {
      name: "Sanjaay Babu",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Philosophy",
      linkedin: "https://www.linkedin.com/in/sanjaay-babu-sg",
      subdivision: "",
    },
    {
      name: "Noa Bremen",
      role: "PM",
      year: 2028,
      majors: "Neuroscience and Econ",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Leah Perlman",
      role: "PM",
      year: 2026,
      majors: "Economics and English",
      linkedin: "https://www.linkedin.com/in/leah-perlman",
      subdivision: "",
    },
    {
      name: "Miriam Leah Ivanenko",
      role: "DKU-Duke Liaison",
      year: 2027,
      majors: "Economics, Chinese Certificate",
      linkedin: "https://www.linkedin.com/in/miriam-leah-ivanenko",
      subdivision: "",
    },
    {
      name: "Kushal Hiremath",
      role: "Analyst",
      year: 2029,
      majors: "Economics and Psychology",
      linkedin: "https://www.linkedin.com/in/kushalhiremath14",
      subdivision: "",
    },
    {
      name: "Danial Hendi",
      role: "Analyst",
      year: 2028,
      majors: "Economics with a Finance Concentration",
      linkedin: "https://www.linkedin.com/in/danialhendi",
      subdivision: "",
    },
    {
      name: "Chloe Tan",
      role: "Analyst",
      year: 2029,
      majors: "Economics and Psychology Minor",
      linkedin: "https://www.linkedin.com/in/chloe-tan-547373216",
      subdivision: "",
    },
    {
      name: "Hipolito Gonzalez",
      role: "Analyst",
      year: 2029,
      majors: "ECE",
      linkedin:
        "https://www.linkedin.com/in/hipolito-gonzalez-gerard-62353a323",
      subdivision: "",
    },
    {
      name: "Jose De Oteyza",
      role: "Analyst",
      year: 2028,
      majors: "Economics and political science",
      linkedin: "https://www.linkedin.com/in/jose-de-oteyza-4963242b4",
      subdivision: "",
    },
    {
      name: "Sawyer Karish",
      role: "Analyst",
      year: 2029,
      majors: "Biology, Evolutionary Anthropology",
      linkedin: "https://www.linkedin.com/in/sawyer-karish-9a6138382",
      subdivision: "",
    },
    {
      name: "Lu jia Lucia Liu Li",
      role: "Analyst",
      year: 2027,
      majors: "Computation; Social Policy",
      linkedin: "https://www.linkedin.com/in/lu-jia-liu-li",
      subdivision: "",
    },
    {
      name: "Kabir Chaudry",
      role: "Analyst",
      year: 2029,
      majors: "Economics and Computer Science",
      linkedin: "https://www.linkedin.com/in/kabir-chaudry",
      subdivision: "",
    },
    {
      name: "Harry Clark",
      role: "",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Jacob Kim",
      role: "",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Diego Keller",
      role: "",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Karthi Ramiah",
      role: "",
      year: 2027,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Antonio Wu Zen",
      role: "",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Selin Mutlu",
      role: "Analyst",
      year: 2029,
      majors: "Mathematics & Education",
      linkedin: "https://www.linkedin.com/in/selin-s-mutlu",
      subdivision: "",
    },
  ],
};
